source 'http://rubygems.org'

gem 'cucumber'
gem 'selenium-webdriver'
gem 'capybara'
gem 'poltergeist'
gem 'pry'
gem 'rspec'
gem 'rspec-retry'
gem 'report_builder'
gem 'slack-notifier'
gem 'rubyzip'
gem 'slack-ruby-client'
gem 'rubocop'